name: backend
description: A sample command-line application.
version: 1.0.0

environment:
  sdk: ^3.5.4

dependencies:
  shelf: ^1.4.1
  shelf_router: ^1.1.4
  bcrypt: ^1.1.3
  dart_jsonwebtoken: ^2.0.0
  dotenv: ^4.1.0
  shelf_cors: ^0.2.0

dev_dependencies:
  lints: ^4.0.0
  test: ^1.24.0
